log-file = "/logs/tiflash_tikv.log"

[readpool]

[readpool.coprocessor]

[readpool.storage]

[server]
engine-addr = "0.0.0.0:4030"
addr = "0.0.0.0:20280"
advertise-addr = "0.0.0.0:20280"
status-addr = "0.0.0.0:20292"

[storage]
data-dir = "/data/flash"

[pd]

[metric]

[raftstore]
capacity = "100GB"

[coprocessor]

[rocksdb]
wal-dir = ""

[rocksdb.defaultcf]

[rocksdb.lockcf]

[rocksdb.writecf]

[raftdb]

[raftdb.defaultcf]

[security]
ca-path = ""
cert-path = ""
key-path = ""

[import]
