#!/bin/bash -e

if [[ ! ${1:-} ]]
then
	echo "please specify the tidb or pd service name! eg: ${0} tidb"
	exit 1
fi

serviceName=${1}
shortName=`echo ${serviceName}|tr -cd '[a-zA-Z]'`
tmpdir="tmp"

# generate a random port
rport=${RANDOM}
[[ ${rport} -lt 10000 ]] && rport=$((rport+10000))

WORKSPACE=$(cd $(dirname $0)/..; pwd)

# change workspace
cd $WORKSPACE
[[ ! -d ${tmpdir} ]] && mkdir ${tmpdir}
docker cp tidbdockercompose_${serviceName}_1:/${shortName}-server ${tmpdir}

pport=`docker port tidbdockercompose_${serviceName}_1|grep -E '[0-9]{5}'|awk -F: '{print $NF}'`

pprof -http=:${rport} ./${tmpdir}/${shortName}-server http://localhost:${pport}/debug/pprof/profile
